# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json
services:
  _defaults:
    autowire: true
    autoconfigure: true

  OpenXE\:
    resource: '../src/'

  Acl:
    class: Acl

  Application:
    alias: erpooSystem
  ApplicationCore:
    alias: Application

  Config:
    class: Config
    factory: ['Xentral\Core\LegacyConfig\ConfigLoader', 'load']

  erpooSystem:
    class: erpooSystem
    arguments:
      $serviceContainer: '@service_container'
    properties:
      Tpl: '@TemplateParser'
      EntityManager: '@Doctrine\ORM\EntityManagerInterface'
      acl: '@Acl'
    calls:
      - SetRequestStack: ['@request_stack']

  Page:
    class: Page

  Player:
    class: Player

  Session:
    class: Session

  TemplateParser:
    class: TemplateParser

  User:
    class: User

  twigpublic:
    alias: twig
    public: true