services:
  OpenXE\:
    resource: '../src/'
    autowire: true
    autoconfigure: true

  Config:
    class: Config
    factory: ['Xentral\Core\LegacyConfig\ConfigLoader', 'load']

  twigpublic:
    alias: twig
    public: true