name: build-docker
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: {context}/docker/Dockerfile
          tags: openxe:${{ github.ref }}